### ISSUE TITLE
Coupling matrix taking too long to compute

### ISSUE THREAD

**Issue by umilta** [LSSTDESC/NaMaster#100]
Hi,

I have set up a script following the guidelines of the pymaster public examples. I am working in flat space and my map is 2500 x 1500 roughly. 

While computing the spin0-spin0 coupling matrix takes a few hours (~4h), computing the spin2-spin2 matrix is taking 100+ hours and is still not completed. Any suggestions on how to speed this up? Any estimates on how longer that spin0-spin0 should this take?

I want to add that I am using the conda version withouth openmp (because I can't install with openmp).

**Comment by damonge** [comment]
Hi @umilta 

Yes, the flat-sky MCM is slow, and scales badly with the number of pixels. There are two ways of speeding it up:
1- Using openmp. Why are you not able to install namaster with openmp?
2- Reducing the L_max (the computation will go like Lmax^2). You can control this through the `NmtBinFlat` object.

**Comment by umilta** [comment]
Hi @damonge,

Unfortunately I can't compile with openmp because I am doing the computation on a cluster and I have limited permission.

I will reduce L_max. Thanks!
