### ISSUE TITLE
 Problems when trying to get the spin-2 field

### ISSUE THREAD

**Issue by gantunesm** [LSSTDESC/NaMaster#102]
Hi, 
I'm using namaster to calculate the cross-correlation between a spin-0 and spin-2 quantities, both defined in a very small part of the sky (fsky ~0.001). However, when I create the fields (f0 and f2), I can't retrieve the spin2- fields, that is, running f2.get_maps()[0] and f2.get_maps()[1] I find both are null (but I am able to find f0.get_maps()[0] fine).
Do you have any idea what could be happening?
I'm not using flat sky approximation (in fact, I would like to compare the results).

Thank you so much!

**Comment by damonge** [comment]
Can you post a snippet of the code you're running? Also, is your mask all made up of normal floating point numbers (i.e. no `healpy.UNSEEN` values, for instance).

**Comment by damonge** [comment]
@gantunesm are you still encountering this issue?

**Comment by damonge** [comment]
I'll close this for now.
