### ISSUE TITLE
Strong B-modes in Q/U Maps When Given Zeroed B Spectrum

### ISSUE THREAD

**Issue by samantha-usman** [LSSTDESC/NaMaster#103]
Hi,

I've been generating maps using NaMaster and finding B-modes in the Q, U map even though I'm getting zeroed-out B spectrum. Here's the command I'm using:
`mpt, mpq, mpu = nmt.synfast_flat(int(fmi.nx),int(fmi.ny),fmi.lx_rad,fmi.ly_rad,np.array([clTT, clTE, 0 * clTT,clEE, 0 * clEE, clTT*0]),[0, 2])`

The Q/U maps generated here look like this:
![image](https://user-images.githubusercontent.com/11999233/80819383-7c9b5300-8b9a-11ea-859a-446ae0e7d41b.png)
![image](https://user-images.githubusercontent.com/11999233/80819388-81600700-8b9a-11ea-938e-c12e7e878673.png)

I then convert these to E/B maps using:
`q_fft = np.fft.rfft2(mpq) * tfac`
`u_fft = np.fft.rfft2(mpu) * tfac`

`e_fft = (+np.cos(tpi_half) * q_fft + np.sin(tpi_half) * u_fft)`
`b_fft = (-np.sin(tpi_half) * q_fft + np.cos(tpi_half) * u_fft)`

`e_map = np.fft.irfft2(e_fft)/ tfac`
`b_map = np.fft.irfft2(b_fft)/ tfac`

which look like this:
![image](https://user-images.githubusercontent.com/11999233/80819468-a81e3d80-8b9a-11ea-8785-69584787915f.png)
![image](https://user-images.githubusercontent.com/11999233/80819479-ac4a5b00-8b9a-11ea-9fbd-4aee4cdcff7c.png)

To test, I also made spectra for the maps and found that the B-spectrum matches the E-spectrum perfectly:
![image](https://user-images.githubusercontent.com/11999233/80825634-672c2600-8ba6-11ea-9450-a93c8bb9d4b5.png)

**Comment by damonge** [comment]
Humm, this could be a sign in the coordinate definition. In your last plot: how have you estimated the spectra? Have you used NaMaster on the Q/U maps?

**Comment by damonge** [comment]
Indeed the patterns in the first two plots suggest pure E and no B, so definitely you should not be getting the same spectrum for both.

What is `tpi_half`?

**Comment by damonge** [comment]
@samantha-usman is this problem still there?

**Comment by samantha-usman** [comment]
@damonge I should've renamed `tpi_half`to `tpi`. Just the phase between between `lx` and `ly`.

`tpi  = 2.*np.arctan2(lx, -ly)`

I'm using my own code to estimate the spectrum. I make the 2D power map, divide it into quarters, then sum over the annuli. I've tested this method against a method made by Joao Caldeira which involves histogramming and both seem to work:
![image](https://user-images.githubusercontent.com/11999233/81183032-3e27de80-8f74-11ea-8165-15ed56061135.png)

But more than that with the spectrum estimate, I also made spectra for simulations made with healpy then projected flat, and got this:
![image](https://user-images.githubusercontent.com/11999233/81183507-de7e0300-8f74-11ea-9348-b19c4869e133.png)
![image](https://user-images.githubusercontent.com/11999233/81183613-f9e90e00-8f74-11ea-9b39-c4e4829b61eb.png)
("Bucket" is simulations from a shared bucket, and "Unlensed" was generated using NaMaster.")

So, the E/B spectra from NaMaster stack almost on top of each other while the sims from Healpy have very little power in the B-spectrum, probably from bleeding due to the conversion. The power in the B-spectrum in the NaMaster maps can't be accounted for from the bleeding though.

(I have a lot of other responsibilities so I'll reply as quickly as I'm able but that might not be immediate.)

**Comment by damonge** [comment]
I'm almost certain this must have to do with the coordinate convention you're using. I'd suggest swapping the sign of `U` before transforming to E/B and see if that does the trick.

**Comment by damonge** [comment]
(see https://github.com/LSSTDESC/NaMaster/blob/8c06824bd37b91ae45cfee447e11dd45eadcb2ca/src/flatsky_utils.c#L112)

**Comment by samantha-usman** [comment]
Hmm, so I followed your suggestion of swapping the sign of U and it looks _a lot_ better. The B map has some teeny structure but it's essentially looks to be zero!

E map:
![image](https://user-images.githubusercontent.com/11999233/81210557-a9cf7300-8f97-11ea-9b55-d45d43e960ba.png)

B map:
![image](https://user-images.githubusercontent.com/11999233/81210583-b5229e80-8f97-11ea-8ef4-a49859bc2ddb.png)

**Comment by damonge** [comment]
Great, thanks a lot!
