### ISSUE TITLE
Covariance matrix with Dl's 

### ISSUE THREAD

**Issue by olakusiak** [LSSTDESC/NaMaster#105]
Hi, 
I am trying to estimate the Gaussian covariance matrix for a simple simulated white noise map (convolved with a beam). It seems to be working fine when I do it for Cl’s, but I get weird (very large) values for my errorbars for Dl’s. 

I tried to follow closely this example: https://namaster.readthedocs.io/en/latest/sample_covariance.html

Do you have any idea what could be wrong? Is there any other part where I should specify is_Dell=True? (besides the bins)

Thank you! 
Here is my code: 

```
import healpy as hp
import numpy as np
import pymaster as nmt 

ellmin=100
ellmax=3100 
Nellbins=15 # number of bins 
nside=2048

#Simulate the map 
cl_white = np.ones(ellmax+1) #ell=0 to ell=ellmax
fwhm_arcmin = 10
bl = hp.gauss_beam(fwhm_arcmin * np.pi/180./60., lmax=ellmax)
cl_sim = cl_white * (bl**2.)
map_sim = hp.synfast(cl_sim, nside, lmax=ellmax) #simulate a map
hp.write_map("workspace/simulated_map.fits", map_sim, overwrite=True)

ell_sim = np.arange(len(cl_sim))
dl_sim = (ell_sim*(ell_sim+1.0)*cl_sim)/(2.0*np.pi) # simulated dl's 

#Mask 
mask="maps/mask_full_v10.fits"
mask=hp.read_map(mask)

#Bins 
ell_ini=[0, 101, 301, 501, 701, 901, 1101, 1301, 1501, 1701, 1901, 2101, 2301, 2501, 2701,2901]
ell_end=[100, 300, 500, 700, 900, 1100, 1300, 1500, 1700, 1900, 2100, 2300, 2500, 2700, 2900,3100]
b=nmt.NmtBin.from_edges(ell_ini=ell_ini, ell_end=ell_end, is_Dell=True) # bins for Dl's 
ell= b.get_effective_ells()

#Fields
f = nmt.field.NmtField(mask,[hp.read_map("workspace/simulated_map.fits", field=0, verbose=False)] )

#Compute master 
dl = nmt.compute_full_master(f, f, b)
dl=dl[0] 
n_ell=len(dl)

#Covariance matrix 
w= nmt.NmtWorkspace()
w.compute_coupling_matrix(f, f, b)
cw = nmt.NmtCovarianceWorkspace()

cw.compute_coupling_coefficients(f, f, f, f, lmax=3099)
covariance = nmt.gaussian_covariance(cw, 0, 0, 0, 0, [dl_sim], [dl_sim],[dl_sim], [d_sim], w, wb=w).reshape([n_ell, 1,n_ell, 1])
covar = covariance[:, 0, :, 0]

#sigmas 
sigma=np.sqrt(covar.diagonal())
print(sigma)

```

**Comment by damonge** [comment]
I don't see anything immediately wrong, although this is a case I have not tested.

When you say the errors are big, do you account for the fact that these are errors on D_ell and not C_ell?

**Comment by damonge** [comment]
Actually, I'm almost sure you should be passing the C_ells and not the D_ells to `nmt.gaussian_covariance` (and I think you have a typo in that line)

**Comment by damonge** [comment]
FYI, I just tried running a modified version of your script and I do get the expected covariance matrix values if I pass in C_ell to `gaussian_covariance`.

**Comment by olakusiak** [comment]
@damonge You're right, I just assumed I should use D_ell in  ```gaussian_covariance```. 
Works perfectly now, thank you!

**Comment by damonge** [comment]
Great. Thanks for reporting this!
