### ISSUE TITLE
libopenblas

### ISSUE THREAD

**Issue by profxj** [LSSTDESC/NaMaster#106]
Installed `pymaster` with conda-forge "successfully" but then received this at import:

```ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory```

Linux Ubuntu 18.0

Did this:

```sudo apt-get install libopenblas-dev```

and all seems happy again.  Just thought I'd share.

**Comment by damonge** [comment]
Thanks! I hadn't encountered this before. I'll add it to the docs.
