### ISSUE TITLE
Coupling matrix computation without input map

### ISSUE THREAD

**Issue by umilta** [LSSTDESC/NaMaster#110]
In the Example 5 you mention that the coupling matrix depends on the masks of the fields to correlate but it is independent of the maps themselves.

Would it be possible to adapt the code to compute the coupling matrix from the mask without requiring an input map too? The map could be generated internally...

**Comment by damonge** [comment]
This could be done, yes. However, a quick workaround would be just to generate a bogus field containing the target mask and a dummy map (which could be the mask itself or anything else, since it's irrelevant). Would this not work?

**Comment by umilta** [comment]
Yes it would work. I was doubtful whether there were some conditions on the input map to be met.  For example, the mask is a bit of a peculiar map, since it is zero on large parts of the mask-array. If you think it will not be a problem to use the mask itself that would basically solve the issue.

**Comment by damonge** [comment]
Yes, the mode coupling matrices only depend on the mask, so whatever map the fields have is irrelevant.
Thanks for reporting this, though. Allowing for "mapless" fields might be something to consider.
