### ISSUE TITLE
What does the flag "is_Dell" in bins.NmtBin exaclty do?

### ISSUE THREAD

**Issue by yaojian95** [LSSTDESC/NaMaster#112]
Hi, I'm using Namaster to calculate the power spectrum of a masked map, for example,  with Nsize = 128. And I will get negative value for the second bin even when I set `nlb=50`. 

But when I turn on the `is_Dell`, the negative values will disappear. However, to my knowledge, `is_Dell` only differs by multiplying with a `ell*(ell+1)/2/pi`, which will not affect the sign of the bandpowers.

Could you give a comment for this phenomenon?

**Comment by damonge** [comment]
@yaojian95 by weighting the pseudo-C_ells differently before mode-decoupling, the structure of the mode-coupling matrix changes a bit, and the result can actually change. This tends to be particularly helpful for red steep spectra, since this weighting essentially whitens the pseudo-C_ells.
