### ISSUE TITLE
rectangular pixellization power spectra

### ISSUE THREAD

**Issue by olakusiak** [LSSTDESC/NaMaster#125]
When I try to follow example 9 from here: https://namaster.readthedocs.io/en/latest/sample_rectpix.html
I encounter a problem with the actual computation of the power spectra with these CAR maps. 

Specifically, when using `nmt.compute_full_master(f0, f0, b)`
where f0 is a spin-0 NmtField created from exactly the same map as in the example (from here https://github.com/LSSTDESC/NaMaster/tree/master/test/benchmarks) and b is some arbitrary binning scheme, I get an error:
`cl1d = lib.comp_pspec(f1.fl, f2.fl, b.bin, None, cln, clg,`
`RuntimeError: Passing inconsistent arguments from python`

I defined the WCS object,  as in the example. 

Has anyone encountered a similar problem?

**Comment by damonge** [comment]
what are the shapes of `cln`, `clg`? And how did you generate `b`?
The power spectra should be populated up to an `ell=f0.fl.lmax`.

**Comment by olakusiak** [comment]
This is my entire script 
```
hdul = fits.open(maps_path)
wcs = WCS(hdul[0].header)
hdul.close()

mask = fits.open(mask_path)[0].data
mp_t, mp_u, mp_q = fits.open(maps_path)[0].data

# Create spin-0 field. Pass a WCS structure do define the rectangular pixels.
f0 = nmt.NmtField(mask, [mp_t], wcs=wcs, n_iter=0)
f2 = nmt.NmtField(mask, [mp_q, mp_u], wcs=wcs, n_iter=0)

ell_max = f0.fl.lmax

#binning
b = nmt.NmtBin.from_lmax_linear(ell_max, 50)
ells = b.get_effective_ells()

cl_00 = nmt.compute_full_master(f0, f0, b)
```
I am not passing any cl_noise or cl_guess, so they both have the same length as defined in compute_full_master, i.e.,
`cln = np.zeros([f1.fl.nmaps * f2.fl.nmaps, 3 * f1.fl.cs.n_eq])`

Am I missing anything here? 

Thank you for your help!

**Comment by xzackli** [comment]
@olakusiak just to make sure the basic test is working, can you navigate to this repository's `test/` directory and run `python sample_rectpix.py`?

**Comment by xzackli** [comment]
Ok, I can reproduce your bug. @damonge perhaps the toeplitz additions changed the python wrapper?

You can get around this by not using the convenience function `nmt.compute_full_master`, and instead creating a workspace, computing coupled spectra, and then decoupling.

```python
b = nmt.NmtBin(2048, nlb=50, lmax=f0.fl.lmax)

# Compute MASTER estimator
# spin-0 x spin-0
lb = b.get_effective_ells()
w0 = nmt.NmtWorkspace()
w0.compute_coupling_matrix(f0, f0, b, n_iter=0)
cl_coupled = nmt.compute_coupled_cell(f0, f0)
Cb = w0.decouple_cell(cl_coupled)
```

**Comment by xzackli** [comment]
Just a little tidying of your MWE:

```python
import matplotlib.pyplot as plt
import pymaster as nmt
from astropy.io import fits
from astropy.wcs import WCS

hdul = fits.open("benchmarks/msk_car.fits")
wcs = WCS(hdul[0].header)
hdul.close()

mask = fits.open("benchmarks/msk_car.fits")[0].data
mp_t, mp_q, mp_u = fits.open("benchmarks/mps_car.fits")[0].data

f0 = nmt.NmtField(mask, [mp_t], wcs=wcs, n_iter=0)
b = nmt.NmtBin(2048, nlb=50, lmax=f0.fl.lmax)
cl_00 = nmt.compute_full_master(f0, f0, b)
```
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-7303e31f3c20> in <module>
     13 f0 = nmt.NmtField(mask, [mp_t], wcs=wcs, n_iter=0)
     14 b = nmt.NmtBin(2048, nlb=50, lmax=f0.fl.lmax)
---> 15 cl_00 = nmt.compute_full_master(f0, f0, b)

~/anaconda3/envs/ps/lib/python3.7/site-packages/pymaster-1.1-py3.7-linux-x86_64.egg/pymaster/workspaces.py in compute_full_master(f1, f2, b, cl_noise, cl_guess, workspace, n_iter, lmax_mask, l_toeplitz, l_exact, dl_band)
    571         cl1d = lib.comp_pspec(f1.fl, f2.fl, b.bin, None, cln, clg,
    572                               len(cln) * b.bin.n_bands, n_iter, lmax_mask,
--> 573                               l_toeplitz, l_exact, dl_band)
    574     else:
    575         cl1d = lib.comp_pspec(f1.fl, f2.fl, b.bin, workspace.wsp,

RuntimeError: Passing inconsistent arguments from python
```

**Comment by damonge** [comment]
Thanks a lot for this @xzackli 
I'm hoping #126 fixes this

**Comment by olakusiak** [comment]
@xzackli thanks a lot, workspace/coupled spectra/decoupling instead of `nmt.compute_full_master` works!

**Comment by damonge** [comment]
@olakusiak the bug in compute_full_master should also be fixed now. Thanks for raising this.
