### ISSUE TITLE
Can't find libsharp? Installed through conda

### ISSUE THREAD

**Issue by fam14c** [LSSTDESC/NaMaster#127]
Hello.
First of all, if this is already a known issue, I apologize.

I installed namaster 1.2 through conda on Python 3.9.2 and attempted to compute the power spectrum of a map. The code crashed with the error message `Illegal instruction (core dumped)`
I ran it through gdb and found the following error message:
```
Thread 1 "python" received signal SIGILL, Illegal instruction.
0x00007ffdcec63f5c in sharp_make_triangular_alm_info (lmax=21600, mmax=21600, stride=1, alm_info=0x7fffffffc6a8)
    at /usr/local/src/conda/libsharp-1.0.0/libsharp/sharp_almhelpers.c:48
48	/usr/local/src/conda/libsharp-1.0.0/libsharp/sharp_almhelpers.c: No such file or directory.
```
I believe this means that libsharp code can't be found, and indeed it's not there. But why is it looking in the wrong place? I installed namaster with conda, so wherever libsharp is, that's where I assume namaster should be looking. How do I fix this issue?

Thank you.

**Comment by damonge** [comment]
OK, we had seen something similar in conda-forge, but couldn't figure out the issue. @beckermr does this throw any light into it?
@fam14c I'd suggest installing from source if possible in the meantime.

**Comment by beckermr** [comment]
This helps but the error doesn't mean the file cannot be found. libsharp is linked in after being compiled. It appears gdb was looking for the file for debugging info maybe?

In any case, where is this routine called @damonge? 

This is either a bug in libsharp or in the way namaster is using libsharp.

**Comment by beckermr** [comment]
Also these lmax values are insane, right?

`lmax=21600, mmax=21600`

**Comment by damonge** [comment]
The function is being called [here](https://github.com/LSSTDESC/NaMaster/blob/3dc363df19d358337616daab09f5e594961faf61/src/healpix_extra.c#L786), but it's the right signature. My guess is that the problem lies with the conda compilers, since libsharp is quite fidgety, but I may be wrong.

21600 is ok if you're using ~half arcmin pixels (e.g. nside=8192, which namaster can handle).

This is kind of frustrating because the conda build is the only case where we've been able to reproduce this error.

The latest master has now moved to libsharp2, so maybe this problem has gone away... It might make sense to tag another minor release...

**Comment by beckermr** [comment]
I'm skeptical about the compilers being the issue given how much other code is being shipped with them and is working fine.

**Comment by beckermr** [comment]
Libsharp2 has no tags or releases so we can't ship it in conda anyways. We should bundle it if we can.

**Comment by damonge** [comment]
Is this a license issue? Because we currently just pull it from gitlab and compile it when installing via setup.py.

**Comment by damonge** [comment]
OK, I guess rather meant the way in which the compilers are used. E.g. [these](https://github.com/LSSTDESC/NaMaster/blob/3dc363df19d358337616daab09f5e594961faf61/scripts/install_libsharp.sh#L26) are the compiler flags we use to compile libsharp2. Are the conda compilers doing this?

**Comment by beckermr** [comment]
We use nocona. I don't think that is the issue

**Comment by beckermr** [comment]
I could be wrong

**Comment by beckermr** [comment]
I've rebuilt libsharp, removing a problematic flag. Once the new build is available, we should retest and see if this bug is still around.

**Comment by beckermr** [comment]
I think the rebuild of libsharp has solved this. Wait a few hours, update your environment, and then try again. You want to make sure libsharp with a build string that ends in 4 is in your env.

**Comment by damonge** [comment]
Thanks a lot @beckermr !

**Comment by beckermr** [comment]
Thank me when it works! 🤞

**Comment by fam14c** [comment]
Hello, sorry for taking so long to reply.

I updated my environment, which included an update to libsharp and pymaster, and now everything works. Thank you.

Regarding the lmax choice, it was the output of pymaster.NmtWCSTranslator(wcs,Ny,Nx).get_lmax(). The wcs and sizes are for the ACT DR4 S15 deep56 field.
I knew that 21000 wasn't very reasonable despite what the function returns. I just did it as a test. The calculation was working, but it was taking too long, so I killed it. Instead I did it with lmax=3000 and binwidth=50 which I believe to be much more reasonable numbers. The resulting spectra look reasonable.

Thank you all for your help.

**Comment by damonge** [comment]
Great, thanks for raising this!
 Yes, the SHTs and MCMs will take a while to calculate with a high ell like that, so you probably want to run that on a large machine.

**Comment by beckermr** [comment]
I am very glad we got to the bottom of this!

**Comment by damonge** [comment]
Me too. Thanks for fixing conda @beckermr
