### ISSUE TITLE
A method to get the alms from the field objects?

### ISSUE THREAD

**Issue by wcoulton** [LSSTDESC/NaMaster#130]
Would it be possible to add a function to the python wrapper that returns the alms contained within the field objects? 
Perhaps by adding another method to the pymaster.field.NmtField class? 

Thanks!!

**Comment by damonge** [comment]
Sure! I actually needed this recently. Can you give #131 a try? It works in my system but would like to check others if possible

**Comment by damonge** [comment]
@wcoulton this was closed automatically when I merged #131 into master, but let me know if the solution I implemented doesn't work for you.
