### ISSUE TITLE
Subtracting Mapping Cross-correlation in Pixel Space

### ISSUE THREAD

**Issue by Zhilei** [LSSTDESC/NaMaster#136]
We have been using the package to measure the C_ell for a cut-sky with proper apodization. Thank you so much for providing the package!

Now we have a question: the map we feed into the algorithm has intrinsic cross-correlation between pixels, mainly from the mapping procedure. We have a good understanding of the cross-correlation. We were wondering whether there is a way to consider the mapping cross-correlation and subtract it from the calculated C_ell.

**Comment by damonge** [comment]
Hi @Zhilei . Can you ellaborate a bit what your model is here? Do you mean that `map_observed_p = sum_p' W_{p,p'} map_true_p'`, where the sum is over pixels? NaMaster is not equipped to deal with that in general unless `W` can be described as an ell-dependent, circularly symmetric, beam.

**Comment by Zhilei** [comment]
I apologize for not explaining this clearly earlier. We are actually trying to use the package on interferometers.
Since the interferometer mapmaking generates grating lobes (as shown in the figure below), the lobes generate an intrinsic power spectrum pattern that is not astrophysical. However, we know the covariance matrix from the mapmaking process very well. We were wondering whether NaMaster can take the mapmaking covariance matrix into consideration and subtract it in the overall map power spectrum.
If NaMaster cannot do that, I was wondering whether you know of any other softwares that can handle this. Thank you so much!
![image](https://user-images.githubusercontent.com/9847573/119827563-47f5ea00-bec7-11eb-8dcc-479653b9e33b.png)

**Comment by Zhilei** [comment]
Hi, David. I was wondering whether you have any suggestions on this. Thanks a lot!

**Comment by damonge** [comment]
Hi @Zhilei 

the answer is (I think) know, as far as I understand the problem. If you can point me to an equation of what the mapmaker is doing exactly I might be able to suggest something else, but at this point I'm not sure what "the lobes generate an intrinsic power spectrum pattern" means exactly (it sounds to me like the effects of a very complicated beam, rather than a power spectrum).

**Comment by Zhilei** [comment]
Hi David! Thank you so much for the input! I have been thinking about this.
I think you are exactly right, it is the effects of a very complicated beam. If we use an example we are familiar with in the CMB community, it will be similar to the little buddies (Fig 6 in this paper https://deepblue.lib.umich.edu/bitstream/handle/2027.42/162636/josaitis.pdf?sequence=1) 
Then the question because whether there is an effective way to take into account the injected correlation from the complicated beam.
Thank you so much!

**Comment by Zhilei** [comment]
Hi, David! Another question I have is whether pymaster can calculate alm's instead of cl's, I did not find the functionality. Maybe I just missed it?

**Comment by damonge** [comment]
Hi @Zhilei . Sorry for the delay.

I haven't thought enough about how to deal with these complicated beams. I believe the buddies were dealt with at the map-making level, for instance. Right now the only beams that can be accounted for in namaster are circularly-symmetric ones described by an ell-dependent Fourier transform.

Regarding alms, pymaster does compute them automatically when generating an `NmtField`. After that, you can access them through `get_alms` ([here](https://namaster.readthedocs.io/en/latest/pymaster.html#pymaster.field.NmtField.get_alms))

**Comment by Zhilei** [comment]
Hi David, no problem at all! Not an urgent issue to begin with.
I am always curious about how the little buddies were accounted for in the analysis, it is good to know that it is handled in the mapmaking stage. Now with my SO beam-calibration-pipeline-developer hat on, we are looking into considering the beam circular asymmetry and how it will affect the final power spectrum, I was wondering whether we should pursue that direction more.
Thank you so much for showing me the `get_alms` function, I will try to use that!

**Comment by Zhilei** [comment]
I just realized I still have the v1.2 version, and it seems like the `get_alms` function hasn't been rolled out until the latest v1.2.1. Can I update to the latest version via `conda`?

**Comment by damonge** [comment]
@Zhilei unfortunately there is a problem with libsharp2 not being part of conda-forge that prevents v1.2.1 from being built in conda-forge. Have you tried installing via pip or from source?

**Comment by Zhilei** [comment]
Hi, David. Thank you so much for the detailed instructions! I was initially hesitant about using pip or from source since I was worried that I will break the system. If you remember I bothered you about the installation a while ago, I am afraid I will run into that again.
Do you think, given my current version installed via conda-forge, I can safely install the latest version with `python -m pip install pymaster [--user]` command?

**Comment by damonge** [comment]
Not sure, it will probably depend on how many python versions you have. However, I would first make sure you really need the `alms` from NaMaster. E.g. could you just use healpy's [map2alm](https://healpy.readthedocs.io/en/latest/generated/healpy.sphtfunc.map2alm.html)?

**Comment by Zhilei** [comment]
I guess the `alms` attribute in the `Field` object is essentially the same as the healpy's map2alm? Because the deprojection does not happen until we calculate the Cls?

**Comment by damonge** [comment]
@Zhilei I forgot I never responded to this. If you need the deprojected version of the alms you could take the maps from namaster and use healpy. Alternatively, the `get_alms` method of `NmtField` should return the alms after deprojection.
