### ISSUE TITLE
Installation by pip

### ISSUE THREAD

**Issue by Nicolo97** [LSSTDESC/NaMaster#137]
Hi,
I'm trying to do the installation by pip but it gives me this error:

Complete output (6 lines):
    running install
    running build
    running build_py
    "." non Š riconosciuto come comando interno o esterno,
     un programma eseguibile o un file batch.
    error: Failed to install libsharp.

I don't know why.
Thanks in advance.

**Comment by damonge** [comment]
@Nicolo97 sorry for the super long delay, I missed this issue. Is this still bugging you?
The error message is a bit obscure. What system are you running this on?
You might also want to try the conda-forge installation, since it might be a bit simpler.
