### ISSUE TITLE
Order of alm output array

### ISSUE THREAD

**Issue by KalusB** [LSSTDESC/NaMaster#145]
Thanks for adding the get_alms function, it is really useful. I am, however, not quite sure to what value of l and m each index of the 1D output array corresponds to. Is it the same as in healpy.sphtfunc.Alm? Thanks in advance for confirming or clarifying this.

**Comment by damonge** [comment]
@KalusB did this help?

**Comment by KalusB** [comment]
Sorry, I thought I had already written a thank you comment. It did help, so thank you 😊
