### ISSUE TITLE
Segfault or NaN for big-endian mask

### ISSUE THREAD

**Issue by zonca** [LSSTDESC/NaMaster#149]
I am experiencing some segfaults when the mask is in big-endian format. It happens sometimes when reading from FITS.
Easy workaround is to turn the mask into little-endian, so it is not critical.

Minimal example:

```python
import healpy as hp 
import numpy as np 
import pymaster as nmt 

nside=32
npix = hp.nside2npix(nside)

mask = np.ones(npix, dtype=">f8")
I_map = np.ones(npix, dtype=np.float64)

f_0 = nmt.NmtField(mask, [I_map])
binning = nmt.NmtBin(nside=nside, 
            nlb=1 , 
            lmax=2*nside, is_Dell=False)
cl_namaster = nmt.compute_full_master(f_0, f_0, binning)
assert not np.isnan(cl_namaster).sum()
```

Sometimes instead of segfaults I get NaN, but currently I cannot seem to reproduce that behaviour.

**Comment by damonge** [comment]
@zonca many apologies for the huge delay on this. I think #161 will fix this. Can I check you'd agree?

**Comment by zonca** [comment]
yes, @damonge, thanks, I confirm the PR fixes it on my system (Debian 10 x86_64)

**Comment by damonge** [comment]
Great, thanks a lot!
