### ISSUE TITLE
NaMaster gives biased Cl values when including a star mask

### ISSUE THREAD

**Issue by AlexMaraio** [LSSTDESC/NaMaster#152]
Hi there,

I'm trying to use the NaMaster code to benchmark the performance of the Pseudo-Cl estimator against the Quadratic Maximum Likelihood estimator for upcoming weak lensing surveys.

One of the aspects that I'm looking at is how the two estimators react to the presence of a star mask, in addition to the main galactic & ecliptic cuts as expected from a space-based observatory.  
First, here is the main mask that one could expect for such an observatory.

![Mask_nostars](https://user-images.githubusercontent.com/9391958/154251554-b5f8c94b-9598-4dfd-9358-b998f318e769.png)

On top of this, I then include a star mask that was built using the prescription for an _Euclid_-like survey as described in Appendix A of [ArXiV: 2010.07376](https://arxiv.org/abs/2010.07376), which gives my mask to be

![Mask_withstars](https://user-images.githubusercontent.com/9391958/154252561-d6ac1dbb-f841-45e1-b834-83bba470de37.png)

To benchmark the estimators, I generate an ensemble of 2,500 maps using a standard ΛCDM cosmology (at a resolution of Nside of 256), add random shape noise in each pixel, and then recover the power spectrum of the maps using the with and without stars masks, without any apodisation.  
While NaMaster is able to perfectly recover the EE and BB spectrum for the mask without stars, it seems that for high _ell_ values, the maps where I have applied the with-stars mask the Cl values are biased high (see plots below).

![Avg_EE_ratio](https://user-images.githubusercontent.com/9391958/154253339-0787d60d-ceb3-42c7-a8e0-839a235e906f.png)
![Avg_BB_ratio](https://user-images.githubusercontent.com/9391958/154253370-a6f422d5-7505-4188-9cb4-49576f73d55a.png)

Given that you have included stars in your demonstration paper of ArXiv: 1809.09603 without issue (see Fig. 3), I am wondering what I might be doing wrong when including stars in my own analysis. Any advice would be much appreciated! 

Many thanks for your time.

**Comment by damonge** [comment]
Hi @AlexMaraio 
In order to interpret these, what kind of `Nside` did you use for these plots?
Note that, when comparing with a theory prediction, you should convolve that theory prediction with the bandpower window functions (you can do that e.g. via `C_binned = w.decouple_cell(w.couple_cell(C_unbinned))`, where `C_unbinned` is the un-binned theory power spectrum. This can be quite important when looking at complicated masks.

**Comment by AlexMaraio** [comment]
Thanks for the quick response @damonge, these plots are for an `N_side` of 256 - and I plot the _ell_ range from `ell = 2` to `ell = 512` for reference. 

For these plots, I am not using binned band-powers (or equivalently I am using band powers with only one _ell_ mode per bin) and so I just got back my original un-binned theory spectrum when computing `C_binned` via your suggested code. This is to compare like-for-like with QML.  
I have just attempted to re-run my simulations implementing binning (with four ell-modes per bin) and I find the same bias being induced in the EE & BB Cl values, even when correcting the theory spectrum for the binning.

Again, any advice is much appreciated.
Thanks again.

**Comment by damonge** [comment]
ok, thanks.

That's a bit puzzling. Do you have a piece of code I could look into that shows how the sims are being generated and the power spectra calculated?

**Comment by AlexMaraio** [comment]
Yeah sure, here's a rough extract showing the computation of the theory Cl values using CCL, the generation of the maps using HealPy (including the addition of shape noise), and the recovery of the Cl values using NaMaster.


```python
ells = np.arange(0, 3 * n_side)
redshift_range = np.linspace(0.0, 3.0, 500)
dNdz = stats.norm.pdf(redshift_range, loc=1.0, scale=0.15)

cosmo = ccl.Cosmology(**{'h': 0.7, 'Omega_c': 0.27, 'Omega_b': 0.045, 'sigma8': 0.75, 'n_s': 0.96, 'm_nu': 0.0, 'T_CMB': 2.7255, 'w0': -1.0, 'wa': 0.0})

# Create E field, and compute EE Cl values
field_E = ccl.WeakLensingTracer(cosmo, dndz=(redshift_range, dNdz))
cl_ee = ccl.angular_cl(cosmo, field_E, field_E, ells)

cl_ee[:2] = 0.0
cl_eb = np.zeros_like(cl_ee)
cl_bb = np.zeros_like(cl_ee)

# Compute mode coupling matrix for mask once
bins = nmt.NmtBin.from_nside_linear(n_side, ells_per_bin)
field_tmp = nmt.NmtField(mask, None, spin=2)
workspace = nmt.NmtWorkspace()
workspace.compute_coupling_matrix(field_tmp, field_tmp, bins)

# Note, the below is done many times
for _ in range(n_sim):
    # Generate signal maps
    alm_E, alm_B = hp.synalm([cl_ee, cl_bb, cl_eb], lmax=3 * n_side - 1, new=True)
    map_Q, map_U = hp.alm2map_spin([alm_E, alm_B], n_side, 2, 3 * n_side - 1)

    # Generate random shape noise maps - then add noise to maps
    noise_Q = np.random.normal(loc=0, scale=noise_std, size=12 * n_side ** 2)
    noise_U = np.random.normal(loc=0, scale=noise_std, size=12 * n_side ** 2)

    map_Q += noise_Q
    map_U += noise_U

    # NaMaster Cl computation
    fields = nmt.NmtField(mask, [map_Q, map_U])
    cl_coupled = nmt.compute_coupled_cell(fields, fields)
    Cl_EE, Cl_EB, Cl_BE, Cl_BB = workspace.decouple_cell(cl_coupled)
```

If you want more detail in the code, do let me know.

**Comment by AlexMaraio** [comment]
Thanks again for your detailed comments. 

I decided to jump straight into the case where I don't add any shape noise, and unfortunately I'm still seeing a bias in the Cl values. Interestingly enough, it seems that the Cl-EE values start to diverge almost exactly at _ell_ = `N_side`, as highlighted with the dashed orange line in the plot below. Not sure what to make of this, as I was under the impression that the Pseudo-Cl's are reliable to at least _ell_ of `2 * N_side`. 

Is there any way to increase the accuracy of the calculations within NaMaster, as perhaps the small-scale nature of the star mask is introducing errors here?

![Avg_EE_ratio_nonoise](https://user-images.githubusercontent.com/9391958/154276486-0b1cb058-dbc3-420d-ab38-1223ad944488.png)

**Comment by AlexMaraio** [comment]
Will try at a larger resolution of `N_side = 1024` now, do you think this is sufficiently accurate?

To generate the star mask, I'm using the `GenStarMask` utility as provided by the [Flask code](https://github.com/ucl-cosmoparticles/flask), described in Section 3.2.2 of the [manual](https://github.com/ucl-cosmoparticles/flask/blob/master/doc/flask_manual.pdf).
This is an executable which takes in six arguments: a random seed, the `N_side` resolution, minimum angular radius for the stars (in arc-mins), maximum angular radius for the stars (again in arc-mins), the sky fraction to be covered by the stars, and an output file name. This basically randomly samples a radius from the given range and then distributes it homogeneously on the sky until the requested sky fraction is achieved. 

As I've said, I'm using numbers for a _Euclid_-like survey as given in 2010.07376, so using minimum and maximum stellar radii of 0.29' and 8.79', respectively, and an f_sky of 20%. This star mask is then superimposed on my existing cuts, which are simply generated using HealPy.
Do let me know if you want any more information, I will update this once I've got data for the increased resolution (make take some time!). Thanks again!

**Comment by damonge** [comment]
OK, thanks a lot. I think 1024 should be enough. Let me know how that turns out!

**Comment by AlexMaraio** [comment]
@damonge Results for my run at `N_side` of 1024 are in, and it seems to show the same scaling behaviour, just shifted to larger _ell_ values:

![Avg_EE_ratio_withoutnoise_1024](https://user-images.githubusercontent.com/9391958/154669416-7614d7b1-526f-4a72-99b2-e9104ef66653.png)

**Comment by damonge** [comment]
OK, interesting. We did not observe this when e.g. analysing realistic HSC data. Perhaps the reason is partly that the mask in practice is not just binary, but actually proportional to the total number of sources in each pixel (or rather the sum of weights), which should reduce the large-ell power of the mask (this is just a guess). It is good to know that this scales with Nside, so that (going to higher Nside) is a possible solution in your case.

One last thing you could try is the following: can you rerun this last test but using `n_iter=0` when creating the `NmtField`s? We have (empirically) found this to improve the behaviour at high-ell for shear-like datasets, with the added advantage that it is also faster than the default.

**Comment by AlexMaraio** [comment]
Thanks for the suggestion for using `n_iter = 0`, however it doesn't seem to change anything in my situation:

![Avg_EE_ratio_niter0](https://user-images.githubusercontent.com/9391958/155141620-bf8db266-6158-4c8f-843c-ae7935f8ed07.png)

Yes I think the practical solution here is to go to double the resolution and then recover the Pseudo-Cl values up to just `l_max = n_side` which should give me accurate results to compare to QML with. 

Thanks again for the help!

**Comment by damonge** [comment]
OK, thanks a lot. I find that surprising, but as I said before it may be due to the choice of mask. It might be worth checking if things change for Nside=1024. I'm glad there's at least a solution.

I'll close this for now, but let me know if you have any other questions and I can reopen.
