### ISSUE TITLE
set_alm of masked map

### ISSUE THREAD

**Issue by xzackli** [LSSTDESC/NaMaster#153]
When running lots of sims, it can be more efficient to construct a field using a_lm of the masked map. The least effort method could be just writing a `set_alm` counterpart to `get_alm`, and re-using a field object. `set_alm` would also be useful in situations where filtering in harmonic space is desired.

**Comment by damonge** [comment]
@xzackli sorry for the delay.

Can I check how you'd like to use this in your pipeline exactly? E.g. imagine you're trying to do the following:

```
import pymaster as nmt
import numpy as np

# 1. Generate dummy field to compute mode-coupling matrix
mask = ...
map = ...
f = nmt.NmtField(mask, map)

# 2. Compute mode-coupling matrix
b = nmt.NmtBin(nside=nside, nlb=10)
w = nmt.NmtWorkspace()
w.compute_coupling_matrix(f, f, b)
cls = []

# 3. Now loop through sims,
#     for which you already have the alms
for alm in alm_sims:
    f.set_alm(alm)
    cl = w.decouple_cell(nmt.compute_coupled_cell(f, f))
    cls.append(cl)
cls = np.array(cls)
```

If so, you can achieve the same simply using healpy's `alm2cl`
```
import pymaster as nmt
import numpy as np
import healpy as hp

# 1. Generate dummy field to compute mode-coupling matrix
mask = ...
map = ...
f = nmt.NmtField(mask, map)

# 2. Compute mode-coupling matrix
b = nmt.NmtBin(nside=nside, nlb=10)
w = nmt.NmtWorkspace()
w.compute_coupling_matrix(f, f, b)
cls = []

# 3. Now loop through sims,
#     for which you already have the alms
for alm in alm_sims:
    cl = w.decouple_cell([hp.alm2cl(alm)])
    cls.append(cl)
cls = np.array(cls)
```
(I've assumed you're dealing with scalar fields above. If you're using spin-2 fields it'd be a matter of giving the output of `hp.alm2cl` the right shape).

Does this help?

I'm happy to be convinced that we should add this in NaMaster, but want to make sure I understand the reasons. Adding this while ensuring that it is consistent with deprojection/purification is not completely trivial.

**Comment by xzackli** [comment]
I'm convinced by this example! Thanks David.
