### ISSUE TITLE
NERSC installation directions should be updated

### ISSUE THREAD

**Issue by lastephey** [LSSTDESC/NaMaster#154]
Dear NaMaster maintainers,

I am on NERSC staff and we recently had a user ticket regarding building NaMaster on Cori. I noticed your current directions are out of date. Several of the modules you were using previously have been retired. Also, we strongly encourage people to build custom software within conda environments rather than with `pip --user`, since that often causes a lot of configuration problems for users. You can read more about this [on our docs page](https://docs.nersc.gov/development/languages/python/nersc-python/#installing-libraries-via-pip).

Here is the build procedure I tested and advice I gave to the user:

```
#ssh to cori

module load python
module load cray-fftw
module unload craype-hugepages2M

conda create -n pymaster python=3.9 -y
conda activate pymaster
conda install gsl cfitsio numpy -c conda-forge

export CC=cc
export CRAYPE_LINK_TYPE=dynamic
export XTPE_LINK_TYPE=dynamic
export LDFLAGS+=" -L$CONDA_PREFIX/lib"
export CPPFLAGS+=" -I$CONDA_PREFIX/include"
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
LDSHARED="cc -shared" CC=cc python -m pip install pymaster --force-reinstall --no-cache-dir

#test by

python -c "import pymaster" 
```

If you can I suggest you try testing this out and if you agree, you can update your NERSC directions. Please let me know if you have any questions.

Thank you,
Laurie

**Comment by damonge** [comment]
@lastephey Thanks a lot for this! And apologies for the delay in responding.

I tested this and I've updated the NERSC installation instructions.
