### ISSUE TITLE
Mask apodization should yield values in [0, 1]

### ISSUE THREAD

**Issue by DanielLenz** [LSSTDESC/NaMaster#17]
I just apodized a boolean mask and found that

```python
>> apod_nmt.max()
1.0000016666803668

>> apod_nmt.min()
-7.494005416219807e-15
```

Could we ensure that these values are in the [0, 1] range, or is this behavior desired? I'd be happy to create a PR to fix this on the python level, simply using [`np.clip(mask, a_min=0, a_max=1)`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html).

**Comment by damonge** [comment]
Since masks are not necessarily 0-1 quantities (e.g. you can use the number of sources in each pixel as the mask for shear maps), I think this shouldn't be implemented on the NaMaster side. Rather users should do whatever modifications they want on the masks before passing on to the code.
