### ISSUE TITLE
configure fails to find cfitsio 

### ISSUE THREAD

**Issue by irene-left** [LSSTDESC/NaMaster#171]
Hi everyone! I am trying to install NaMaster on Macos M2 using the clone github method in a new environment (env_new)and I run into the following error after running `(env_new) el@irenes-mac NaMaster % pip install .` : <br>
`configure: error: could not find the cfitsio library` 
  `ERROR: failed to configure HEALPix. Check CFITSIO is installed and reachable.` 
      `error: Failed to install libchealpix.` 
      `[end of output]` 
 
  `note: This error originates from a subprocess, and is likely not a problem with pip.` 
`error: legacy-install-failure` 

`× Encountered error while trying to install package.` 
`╰─> pymaster` 

`note: This is an issue with the package mentioned above, not pip.` 
`hint: See above for output from the failure.`

Could anyone help me figure out how to make this work ? I have already installed cfitsio in my mac on a different directory home/cfitsio if that helps. Thank you !

**Comment by fjaviersanchez** [comment]
Hi! Have you tried running `LDFLAGS+=-L/path/to/cfitsio/lib` and `CFLAGS+=-I/path/to/cfitsio/include"` prior to running `pip install .`?

**Comment by irene-left** [comment]
> Hi! Have you tried running `LDFLAGS+=-L/path/to/cfitsio/lib` and `CFLAGS+=-I/path/to/cfitsio/include"` prior to running `pip install .`?

Thank you so much for the response. Just tried this and unfortunately I still run into the same error.

**Comment by damonge** [comment]
@irene-left just checking that you replaced `/path/to/cfitsio/lib` with the actual path to where the cfitsio lib is installed :-)

**Comment by irene-left** [comment]
@damonge yes the full path to where cfitsio is installed is `User/el/cfitsio` so I have changed `LDFLAGS+=-L/User/el/cfitsio/lib`. and `CFLAGS+=-I/User/el/cfitsio/include` but the same error still occurs :( -- I am fairly new to manually configuring and building libraries on a terminal so apologies if what I am saying sounds trivial--

**Comment by irene-left** [comment]
@fjaviersanchez Just tried this and unfortunately still getting an error : <br> 
<img width="581" alt="Screenshot 2023-05-17 at 12 44 06" src="https://github.com/LSSTDESC/NaMaster/assets/115017808/37d515c4-825e-4add-b93d-d84190bbe98b">

**Comment by damonge** [comment]
I believe the new version of NaMaster on conda should solve this issue in practice. If that's not the case, please feel free to reopen.
