### ISSUE TITLE
Error when setting lmax < 3 * nside - 1 in compute_full_master

### ISSUE THREAD

**Issue by j-dr** [LSSTDESC/NaMaster#176]
Hi NaMaster devs,

I'm running into a problem when I try to run compute_full_master on fields where I've set lmax_sht<3*nside-1. 

Here's a minimal example:

```
nside = 256

#setup maps
m = np.ones(12*nside**2)
em1 = np.ones(12*nside**2)
em2 = np.ones(12*nside**2)

#setup binning
lbins = nmt.NmtBin(nside=nside, nlb=25, lmax=nside)

#setup fields and compute things
f1 = nmt.NmtField(m, [em1, em2], lmax_sht=nside, lite=True)
wsp = nmt.NmtWorkspace()
wsp.compute_coupling_matrix(f1, f1, lbins, lmax_mask=nside)
cl_coup = nmt.compute_full_master(f1, f1, lbins, workspace=wsp, lmax_mask=nside)
```

and the backtrace:

![image](https://github.com/LSSTDESC/NaMaster/assets/5467294/fbb44bc9-1bff-443c-a1b5-a70b388423df)

The analogous code that doesn't set `lmax` anywhere does not throw such an error. In all likelihood I'm just doing something wrong, but I couldn't quite figure out what, so any tips would be appreciated.

Thanks!

**Comment by damonge** [comment]
Hi @j-dr . Can I check what version of namaster you're using? The latest one on pip should have this fixed.

Running this same script will throw another error (to do with deprojection), but you can get around it setting `lite=False`. I'll make a quick patch so this is not needed in any case.

**Comment by j-dr** [comment]
Ah, I was on v1.0.1! Just updated and things work. Sorry for the noise!
