### ISSUE TITLE
Missing different lmax for mask and coupling coefficients for covariances

### ISSUE THREAD

**Issue by carlosggarcia** [LSSTDESC/NaMaster#179]
At the moment, the coupling coefficients covariances can accept a `lmax`:

https://github.com/LSSTDESC/NaMaster/blob/b45317f840320855b7e38799fa411782e2886289/src/nmt_covar.c#L48

Ideally we would have one for the coupling coefficients and another for the mask, like in the case of the `NmtWorkspace`

**Comment by damonge** [comment]
Somehow I never closed this issue. It's now been solved.
