### ISSUE TITLE
Floating point errors with full sky CAR pixellization

### ISSUE THREAD

**Issue by adrien-laposta** [LSSTDESC/NaMaster#203]
Loading a CAR map into a `NmtField` object, a check on the angular range of the map (Right Ascension) is performed during the  `NmtMapInfo` object initialization. 
https://github.com/LSSTDESC/NaMaster/blob/0769c82230b8a1d5b5a739098f0f56bc309fa3be/pymaster/utils.py#L340

Due to floating point errors while computing this condition, the result can be `>360` for a full sky CAR map and raise an error.

A quick fix would be to allow for small variation in the `if` statement, e.g `np.fabs(nx*d_ra)>360+1E-7`

**Comment by damonge** [comment]
@adrien-laposta this should now be fixed. New version is on pip and hopefully soon on conda
