### ISSUE TITLE
Make full-sky spectra agnostic to pixelization and/or add support for rectangular pixels 

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/NaMaster#21]
Copying an issue initially opened by @msyriac in the old NaMaster repo:

David, do you have an idea of how much work this would involve? It does look like key modules like nmt_mask.c are explicitly written for healpix pixels, at least in terms of function arguments. Would adapting these modules require converting logic that is hard-coded for healpix?

**Comment by damonge** [comment]
@msyriac thanks for opening this one.
This is at the top of my list once the NaMaster paper is out.
I think the main roadblock would be to understand how libsharp uses other pixelization schemes. The rest should be relatively simple to rewrite, since only a few very specific functions make use of built-in healpix subroutines (e.g. the mask apodizers).
In the meantime you have the flat-sky version...

**Comment by xzackli** [comment]
I'd like to work on this issue, for the purpose of working with ACT maps! I've talked a little to @msyriac about this already.

**Comment by damonge** [comment]
OK, great! It'd be great if you guys can have a chat with either Sigurd or Steve Choi at some point. I know there are some subtleties regarding how CAR is interpreted by libsharp, but once those are clarified, it should be easy.

I'd like to be involved in this, although I'll be crazy busy for at least the next week. I can answer any questions you have though.

All the pixel manipulation, currently done in healpix, is taken care of at the C level by [healpix_extra.c](https://github.com/LSSTDESC/NaMaster/blob/master/src/healpix_extra.c).

**Comment by xzackli** [comment]
The `rectpix_both` branch now has CAR support for both spin 0 and 2. Three main things still need doing,

1. I have to add `nmt_workspace_CAR` read/write functions.
2. Neither mask apodization nor templates/deprojection are tested.
3. Unit tests! Documentation!

**Comment by msyriac** [comment]
Nice! Is your implementation really specific to CAR, or is it perhaps more general to cylindrical projections or rectangular pixels?

**Comment by xzackli** [comment]
It would be easy to use any ring weight scheme that libsharp already supports. This is actually more limited than general CAR -- libsharp supports equidistant cylindrical projection grids (ECP), i.e. the colatitude rings must be evenly spaced and divide the sphere evenly, [see libsharp paper.](https://arxiv.org/pdf/1303.4945.pdf)

**Comment by xzackli** [comment]
You're right, I've deleted `rectpix` since it doesn't have anything useful anymore!

**Comment by xzackli** [comment]
Solved by PR #39
