### ISSUE TITLE
Follow up on failing test 41 in Mac OS 

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/NaMaster#22]
This issue is to check if there's a quick fix to solve the failing test #41/53 in Mac OS.

**Comment by damonge** [comment]
This is not generic, right? I think we only see it when clang has been used for part of the compilation. Is this right @fjaviersanchez ?

**Comment by fjaviersanchez** [comment]
Since NaMaster is dependent in OMP most people won't use clang (there's a way to include OMP in clang but it is easier to get gcc from Homebrew or similar). I installed the code using gcc from homebrew and I got the failed test. I think this is architecture related (probably some optimization flag that we shouldn't be using with gcc+homebrew) but I'd like to check it out just to make sure.

**Comment by damonge** [comment]
OK. It'd be good to check which specific `assert` statement fails. This one should be easy to figure out. Unfortunately I don't have direct access to a mac.

**Comment by damonge** [comment]
Hey @fjaviersanchez . @beckermr recently found a silly bug just before this line, so I suspect that this is now fixed. Can you check when you get a minute?

**Comment by fjaviersanchez** [comment]
Thanks @damonge @beckermr! It works now. I am going to close this.
