### ISSUE TITLE
ImportError: No module named '_nmtlib'

### ISSUE THREAD

**Issue by brandonshensley** [LSSTDESC/NaMaster#23]
I'm very eager to use NaMaster for research and appreciate you making it available. I'm stuck on the installation step and am hoping I'm just stumbling over something obvious. Any insights much appreciated.

I have successfully compiled the NaMaster C code, with

`./configure`
`make`
`make install`
`make check`

all running fine and all checks passing (well, test 20 appears to be skipped). However, I've been having trouble with the python wrapper. Note that I am on a Mac, running High Sierra 10.13.6, and having installed many of the requisite libraries with MacPorts (hence the directory '/opt/local/lib' below).

The command

`python setup.py install`

looks to run normally, but when I then try

`python`
`>> import pymaster`

I get the error

> Traceback (most recent call last):
>  File "/Users/bhensley/.local/lib/python3.6/site-packages/pymaster/nmtlib.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_nmtlib', [dirname(__file__)])
  File "/anaconda3/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_nmtlib'
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bhensley/.local/lib/python3.6/site-packages/pymaster/__init__.py", line 40, in <module>
    from pymaster import nmtlib as lib
  File "/Users/bhensley/.local/lib/python3.6/site-packages/pymaster/nmtlib.py", line 28, in <module>
    _nmtlib = swig_import_helper()
  File "/Users/bhensley/.local/lib/python3.6/site-packages/pymaster/nmtlib.py", line 20, in swig_import_helper
    import _nmtlib
ImportError: dlopen(/Users/bhensley/.local/lib/python3.6/site-packages/_nmtlib.cpython-36m-darwin.so, 2): Library not loaded: libchealpix.dylib
  Referenced from: /Users/bhensley/.local/lib/python3.6/site-packages/_nmtlib.cpython-36m-darwin.so
  Reason: image not found

However, when I add the following my .bash_profile:

`export DYLD_LIBRARY_PATH='/opt/local/lib'`

pymaster imports fine without complaint and even passes some unit tests. Note that that directory is where libchealpix.dylib lives. Unfortunately, whenever I have that line in my .bash_profile, healpy cannot be imported (and so all healpy-dependent unit tests fail). I haven't had any luck with things like adding '/opt/local/lib' to my LD_LIBRARY_PATH and LDFLAGS and am running out of ideas. Any help very much appreciated. Thanks!

**Comment by fjaviersanchez** [comment]
Hi @brandonshensley,

I would say (but not 100% sure) that the C Healpix library shipped with MacPorts is not the same version that `healpy` is internally using (if you did `pip install healpy` I think that it pulls and installs a copy of `libchealpix` if it doesn't locate one) and when you try to import `healpy` it conflicts with the newly-loaded healpix library. If this is the case, you can set the environment variable `export DYLD_LIBRARY_PATH='/opt/local/lib'` and then reinstall healpy `pip install --upgrade --force-reinstall healpy`. If this doesn't work we'll need to check out the installing code.

**Comment by fjaviersanchez** [comment]
:( I think it's getting kind of confused between the system and the macports libraries, what if you try with `export DYLD_LIBRARY_PATH='/opt/local/lib:/usr/lib:/usr/local/lib'`? Does it still die?

**Comment by brandonshensley** [comment]
Amazingly, that broke _both_ pymaster and healpy! Just `export DYLD_LIBRARY_PATH='/opt/local/lib:/usr/local/lib'` returned pymaster to functionality but with healpy still unable to be imported. I am also kind of confused...

**Comment by brandonshensley** [comment]
Progress! Setting instead `export DYLD_FALLBACK_LIBRARY_PATH='/opt/local/lib'` lets me import both. (I confess I don't really understand why) However, I am still failing three unit tests, unsure if it is related to the issues I've been having:

```
FAIL: test_mask_c1 (test.test_nmt_utils.TestUtilsMaskSph)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bhensley/Software/NaMaster/test/test_nmt_utils.py", line 215, in test_mask_c1
    self.assertTrue((np.fabs(msk_apo[self.th<self.th0-np.radians(self.aposize)]-1.)<1E-10).all())
AssertionError: False is not true

======================================================================
FAIL: test_mask_c2 (test.test_nmt_utils.TestUtilsMaskSph)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bhensley/Software/NaMaster/test/test_nmt_utils.py", line 227, in test_mask_c2
    self.assertTrue((np.fabs(msk_apo[self.th<self.th0-np.radians(self.aposize)]-1.)<1E-10).all())
AssertionError: False is not true

======================================================================
FAIL: test_synfast_flat_stats (test.test_nmt_utils.TestUtilsSynfastFsk)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bhensley/Software/NaMaster/test/test_nmt_utils.py", line 114, in test_synfast_flat_stats
    self.assertTrue(get_diff(ctt1,self.cltt,self.cltt,self.cltt,self.cltt,nk).all())
AssertionError: False is not true

```

**Comment by fjaviersanchez** [comment]
🎉 glad to hear! I think that it might be related.

I would try to reinstall healpy using the ports version of `libchealpix` (which I am not sure how to do because it seems that it can't find the `_icov` library... An option can be maybe creating a link in `/usr/local/lib` to `/opt/local/lib/libcheakpix.dylib` but I am not convinced that will work) or download HEALPix and compile from source:

```wget https://sourceforge.net/projects/healpix/files/Healpix_3.11/autotools_packages/chealpix-3.11.4.tar.gz && tar xzf chealpix-3.11.4.tar.gz && cd chealpix-3.11.4 && ./configure --enable-shared && make && sudo make install && cd ..```

And then: `pip install --upgrade --force-reinstall healpy`

**Comment by brandonshensley** [comment]
Success! What finally worked was uninstalling my conda installation of healpy and reinstalling with the "--no-deps" flag. I was never able to get healpy to install properly via pip, but it seems like others are also having trouble on macOS 10.13. One lingering thing is a warning during the tests:

```
test_workspace_compute_coupled_cell (test.test_nmt_master.TestWorkspaceSph) ... /anaconda3/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
```

but since all tests pass now I'll close the issue and report back if I experience any problems running the code. Thanks so much for all of the help!

**Comment by fjaviersanchez** [comment]
I am glad it worked. Please, feel free to open this again if you experience any other related problems and thanks for reporting your solution.
