### ISSUE TITLE
provide a no openmp option and use FFTW with pthreads instead of openmp

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/NaMaster#34]
OpenMP doesn't play nice with python multiprocessing. The OpenMP code not in FFTW doesn't look so bad that no openmp there would be a disaster. For the FFTW code, you can link to the pthreads library without changing any of the source. The only changes to the repo then are in some makefiles, the setup.py and some documentation.

Thus I think providing a no openmp option should be feasible. You can see the patches I am using with the conda package [here](https://github.com/conda-forge/staged-recipes/pull/7194/files).

Thoughts?

**Comment by beckermr** [comment]
Related to https://github.com/conda-forge/staged-recipes/pull/7194

**Comment by damonge** [comment]
Unfortunately I've never used pthreads (shame on me), so a priory I don't know how much work this would be

**Comment by beckermr** [comment]
None. See the patches I linked.
