### ISSUE TITLE
Missing file for tests

### ISSUE THREAD

**Issue by msyriac** [LSSTDESC/NaMaster#45]
In branch:rect_dam
```
> python -m unittest discover -v
FileNotFoundError: [Errno 2] No such file or directory: 'test/benchmarks/msk_car.fits'
```

**Comment by damonge** [comment]
Yeah, we're still converging on the unit tests for CAR. Will make sure everything is there before meging!

**Comment by damonge** [comment]
This is now fixed in the same branch
