### ISSUE TITLE
Locating Libsharp issue

### ISSUE THREAD

**Issue by jhparkes** [LSSTDESC/NaMaster#53]
Hello,

I am sorry that this is a simple issue. I have been trying to install NaMaster without using Conda. I followed the instructions for downloading the dependencies and as far as I can tell Libsharp installed correctly. However, when I run ./configure for NaMaster I get the following issue:

"checking for library containing sharp_Ylmgen_destroy... no
configure: error: Couldn't find libsharp"

I believe that it has to do with NaMaster not knowing what directory Libsharp is in. In my system it is located at /mnt/d/ubuntu/libsharp-1.0.0/ I was wondering if someone could point me in the direction of how to correct this issue.

Thank you.

**Comment by damonge** [comment]
Hi @jhparkes 

I think this should be easy to sort out: you need to make sure that:
- The environment variable `LD_LIBRARY_PATH` contains the path to the directory where the libsharp libraries live (you can do this through `export LD_LIBRARY_PATH=/path/to/libsharp/lib:$LD_LIBRARY_PATH`)
- The similar thing for `LDFLAGS` and `CPPFLAGS`. In this case you'd want:
```
export LDFLAGS+=" -L/path/to/libsharp/lib"
export CPPFLAGS+=" -I/path/to/libsharp/include"
```
Note that the directories `/path/to/libsharp/lib` and `/path/to/libsharp/include` must exist and must contain the `lib***` and `***.h` files installed by libsharp.

You can probably adapt the contents of the [NERSC_Installation.md](https://github.com/LSSTDESC/NaMaster/blob/master/NERSC_installation.md) document to your own system when doing this.

Let me know if this doesn't work

**Comment by jhparkes** [comment]
Hey @damonge 

Thank you so much. That worked. I was able to successfully run the ./configure file after using the process above for both Libsharp and Healpix. I have also confirmed that Healpix seems to be working by running the test discussed in the Healpix test/README. 

I am now running into an issue where the make is running into a fatal error. It seems that it is related to it not being able to find chealpix.h. But I have confirmed that there is a file by that name in the directory /path/to/healpix/src/C/autotools/. I am slightly confused about how to add this to the path and where to add it to. I have added the healpix/lib and /include directories as above but not /src/C/autotools. The exact error I am getting is:

make  all-am
make[1]: Entering directory '/mnt/d/GradSchool/ubuntu/NaMaster.git/trunk'
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -fopenmp -I./src/   -g -O2 -MT src/libnmt_la-healpix_extra.lo -MD -MP -MF src/.deps/libnmt_la-healpix_extra.Tpo -c -o src/libnmt_la-healpix_extra.lo `test -f 'src/healpix_extra.c' || echo './'`src/healpix_extra.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fopenmp -I./src/ -g -O2 -MT src/libnmt_la-healpix_extra.lo -MD -MP -MF src/.deps/libnmt_la-healpix_extra.Tpo -c src/healpix_extra.c  -fPIC -DPIC -o src/.libs/libnmt_la-healpix_extra.o
src/healpix_extra.c:3:22: fatal error: chealpix.h: No such file or directory
compilation terminated.
Makefile:726: recipe for target 'src/libnmt_la-healpix_extra.lo' failed
make[1]: *** [src/libnmt_la-healpix_extra.lo] Error 1
make[1]: Leaving directory '/mnt/d/GradSchool/ubuntu/NaMaster.git/trunk'
Makefile:424: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by damonge** [comment]
Right, this can probably be solved in a similar manner, but I'm thinking that using the conda forge version of NaMaster might be much easier. Have you tried following the instructions at the beginning of the README?

**Comment by jhparkes** [comment]
I did try that. However, when I did for some reason I ran into a different issue that whenever I ran python in a conda environment I could import pymaster I could not import healpy. I tried figuring out the source of this error for a long time and couldn't ever uncover it. That is why I decided to try the alternative method

**Comment by damonge** [comment]
Oh well. OK, let's go back to the healpix problem then. 

> I have added the healpix/lib and /include directories as above but not /src/C/autotools. 
Is there no `chealpix.h` file in this include directory?

**Comment by jhparkes** [comment]
There is a chealpix.h in the include directory. I had missed it last time I looked

**Comment by damonge** [comment]
OK, you want to add those lib and include directories to `LDFLAGS`, `LD_LIBRARY_FLAGS` (lib) and `CPPFLAGS` (include), and then rerun `./configure`. Have you done that?

**Comment by jhparkes** [comment]
Yes, I actually had to add them in order to get ./configure to run
