### ISSUE TITLE
Usage of CovarianceWorkspace.compute_coupling_coefficients()

### ISSUE THREAD

**Issue by YutoMinami** [LSSTDESC/NaMaster#58]
I use the NaMaster gotten from conda-forge.
In example 8:  NaMaster/test/sample_covariance.py,
the function, compute_coupling_coefficents(), requires four fields.
However, the actual required arguments seem to be two NmtWorkspaces.
Then, should I pass two NmtWorkspaces of two spin-0 fields to the function to calculate copuling coefficients even if I want a covariance of spin-2 fields?

**Comment by damonge** [comment]
Hi @YutoMinami 

can I check that you're using the latest version of the conda-forge code? We updated it fairly recently and the covariance part changed substantially. When did you download it?

**Comment by YutoMinami** [comment]
Hi @damonge 
I checked with revision history.
It says I installed namaster-0.9 on 2019/05/29.
As far as I checked in anaconda cloud, https://anaconda.org/conda-forge/namaster, it's the latest one.
Isn't it?

**Comment by damonge** [comment]
Mmmh, there should be a v1.0. Let me have a look (@beckermr may have faster answers here)

**Comment by beckermr** [comment]
Looks like a conda-forge build failed. Try again to install in about 30 minutes and it should have 1.0.

**Comment by beckermr** [comment]
This was a transient github outage from like a month ago that killed a CI job. Yay!

**Comment by damonge** [comment]
@beckermr for the win! Thanks a lot.

**Comment by YutoMinami** [comment]
Thank you @beckermr @damonge .
I found the version changed in anaconda cloud. I will install them and try.

**Comment by YutoMinami** [comment]
It worked. Thanks!
