### ISSUE TITLE
lmax option in gaussian_covariance()

### ISSUE THREAD

**Issue by YutoMinami** [LSSTDESC/NaMaster#59]
I got error in using "gaussian_covariance" funcion as:
Traceback (most recent call last):
  File "MakeCovariance.py", line 79, in <module>
    w22, wb=w22
  File "/home/cmb/yminami/.pyenv/versions/anaconda3-5.1.0/envs/fgenv/lib/python2.7/site-packages/pymaster/covariance.py", line 223, in gaussian_covariance
    wa.wsp, wb.wsp, cla1b1, cla1b2, cla2b1, cla2b2, len_a * len_b
RuntimeError: Coupling coefficients only computed up to l=4096, but you requirelmax=6143. Recompute this workspace with a larger lmax

I'd like to use lmax to be 2*nside, and nside =2048.
I prepared coupling coefficients in NmtCovarianceWorkspace with lmax=nside*2, set NmtWorkspace.lmax=nside*2 by hand, and cls with lmax=nside*2.
Though I think these are all arguments which have lmax information, it fails.

Could you please tell me the best way to set lmax in the calculation of covariance matrix?

**Comment by YutoMinami** [comment]
I'm sorry I overlooked another closed issue and setting lmax in NmtBin solved all.

**Comment by damonge** [comment]
Great, thanks for reporting this @YutoMinami . Which issue helped you (just thinking it'd be good to have a reference here).

**Comment by YutoMinami** [comment]
It's in this issue, https://github.com/LSSTDESC/NaMaster/issues/18.
It  seems, in "gaussian_covariance", ell_max variable in wsp.bin is used and I assume this bin is from NmtBin, even though there is a lmax variable direct below wsp.

**Comment by damonge** [comment]
Ah, great. Thanks again!
