### ISSUE TITLE
Additional NERSC installation instructions

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/NaMaster#62]
Just opening a permanent issue in case it's useful for others. Note that the [NERSC_installation.md](https://github.com/LSSTDESC/NaMaster/blob/master/NERSC_installation.md) instructions have been updated after the Cori upgrade, so I'd advice to try those first.

@akrolewski reports the following (many kudos to him!):

after the recent nersc upgrade, found that I needed to do a few more things than you had enumerated on your "nersc_installation" [readme](https://github.com/LSSTDESC/NaMaster/blob/master/NERSC_installation.md) on github. (which was very helpful by the way).  I don't know how many of these issues are specific to my setup or are more generic, but I figured I'd pass this along in case it can be helpful to others (and am happy to add some notes to github as well, if you think it's useful).

These were as follows:

1.  I couldn't get the healpix installation to work, but I instead was able to get away with using the pre-installed healpix on nersc.  This meant that my .bashrc.ext looked like the following:
```
export PATH=$HOME/bin:/global/common/cori/contrib/hpcosmo/hpcports_gnu-4.0/healpix-3.30.1_62c0405b-4.0/bin:$PATH
export LD_LIBRARY_PATH=$GSL_DIR/lib:/opt/cray/pe/fftw/3.3.6.3/haswell/lib:/global/common/cori/contrib/hpcosmo/hpcports_gnu-4.0/healpix-3.30.1_62c0405b-4.0/lib:$LD_LIBRARY_PATH:$HOME/lib
export LDFLAGS+=" -fopenmp -L$GSL_DIR/lib -L$HOME/lib -L/global/common/cori/contrib/hpcosmo/hpcports_gnu-4.0/healpix-3.30.1_62c0405b-4.0/lib -L/opt/cray/pe/fftw/3.3.6.3/haswell/lib"
export CPPFLAGS+=" -fopenmp -I$GSL_DIR/include -I/usr/common/software/cfitsio/3.370-reentrant/hsw/intel/include -I$HOME/include -I/global/common/cori/contrib/hpcosmo/hpcports_gnu-4.0/healpix-3.30.1_62c0405b-4.0/include"
export CC=cc
```

2. I've always found that I needed to add the following when compiling:
`module load cray-fftw`

3.  (I believe the instructions in the updated [NERSC_installation.md](https://github.com/LSSTDESC/NaMaster/blob/master/NERSC_installation.md) should take care of this one). When trying to set up pymaster, I ran into a bug where python couldn't find libgsl.so.19 (but the c-code namaster worked fine, it was just an issue with pymaster):
`ImportError: libgsl.so.19: cannot open shared object file: No such file or directory`
So I created a symbolic link to libgsl.so.23 in my `$HOME/lib` directory:
`ln -s $GSL_DIR/lib/libgsl.so.23 libgsl.so.19`

4.  I found that while pymater worked fine on the login nodes, on the compute nodes I got the following error:
`seg 0, mem 0: remap(0x555555754000,0x2000,0x2000,0x3,0x2aaaaab18000) failed, error 14`
I got around this (thanks to Rollin Thomas at NERSC) by doing `module unload craype-hugepages2M` before compiling, and then also `module unload craype-hugepages2M` before running pymaster.

**Comment by xzackli** [comment]
Problem #4 doesn't seem to affect GCC builds of NaMaster on NERSC. However, in order to get multithreading to work with GCC, I had to append `-lgomp\ -fopenmp` to  `CFLAGS` before running `python setup.py install` -- otherwise it would just stay on one thread.

**Comment by damonge** [comment]
@akrolewski : is there a NERSC ticked describing the `craype-hugepages2M` issue you mentioned?
I'm having similar issues with other codes, and I'd like to get to the bottom of this.

**Comment by rcthomas** [comment]
Hi, I'm from NERSC.  After the July/August upgrade we advised users to disable `craype-hugepages2M` when compiling extensions from source, specifically this appeared in our directions on building mpi4py against Cray MPICH.  However I believe this is no longer an issue.

Have you considered doing a build in a centralized location like [/global/common/software](https://docs.nersc.gov/filesystems/global-common/) for your users at NERSC?  The benefits would be:

- Centralized installation, users no longer need to compile everything from source to use it
- As the maintainers you have an idea of what they're running if they report issues
- The /global/common filesystem is mounted read-only from Cori compute nodes with DVS client-side caching turned on, which helps to alleviate the slow-launch problem Python has at scale
- You could provide a blessed way to use the package from Jupyter@NERSC by providing a kernel, with some of the above benefits

If you have questions please don't hesitate to ask.

**Comment by damonge** [comment]
Thanks a lot @rcthomas , and sorry for the slow reply.
I didn't know this was an option, but it sounds great. I'll look into it and reach out if I have questions.
Thanks!

**Comment by damonge** [comment]
Installation instructions updated as per #154
