### ISSUE TITLE
make check failed on test/check_nmt

### ISSUE THREAD

**Issue by ittpmichael** [LSSTDESC/NaMaster#67]
Hi,

I have built NaMaster with these following packages provided by OpenHPC repo:

* gnu8/8.3.0 (GCC)
* mvapich2/2.3, openmpi3/3.1.3
* fftw/3.3.8
* gsl/2.5
* libsharp compiled with either mvapich2 or openmpi3

and with healpix.x86_64 and chealpix.x86_64 from **epel** repo. The OS is CentOS7 (3.10.0-957.el7.x86_64).

The `make check` processes are failed on 
```
TEST 34/66 nmt:bins_f_ell [FAIL]
  ERR: test/nmt_test_bins.c:30  expected 5.252e+05, got 5.252e+05 (diff -1.164e-10, tol 1.000e-10)
```

**Comment by damonge** [comment]
sorry for the delay @ittpmichael . This seems like a very weird floating point error that would be difficult to track down... I suggest to ignore this. I'll just raise the tolerance a bit on this one. Thanks a lot!

**Comment by damonge** [comment]
Solved by #71

**Comment by ittpmichael** [comment]
I can reproduce this error and I finally know what causes this `make check` to be failed. This is because I set `CFLAGS=-Ofast`. For other flags like `-O4` or `-O3` are working fine.

**Comment by damonge** [comment]
Aha, good detective work! Thanks a lot for reporting this!
