### ISSUE TITLE
latest libsharp

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/NaMaster#70]
We should try and move to the latest version of libsharp, which is currently hosted in gitlab (https://gitlab.mpcdf.mpg.de/mtr/libsharp). I just found out about this now

**Comment by damonge** [comment]
Kudos to @gfabbian for bringing this up

**Comment by damonge** [comment]
Solved by #71

**Comment by xzackli** [comment]
The main change is that `ntrans` is no longer a parameter for `sharp_execute`.  You'll have to transform the 0 and 2 maps with two calls to `sharp_execute`, I think. I also had some trouble getting the `sharp_Ylmgen_destroy` function from `configure.ac` to be found.

**Comment by gfabbian** [comment]
It's slightly more complicated than that as also the FFT library and linking changed. I got it running at NERSC with the lib sharp version distributed in Healpix 3.5 and with the version checked out from the repo. Any preference how to solve this? In order to keep the support for all library version then some preprocessing statements in the code to be specified when compiling should be enough.

**Comment by damonge** [comment]
Hey @gfabbian . Did you have to modify NaMaster itself (including the configure scripts)? If so, a PR form a fork would be ideal (as would any instructions to reproduce what you had to do).

**Comment by gfabbian** [comment]
Yes, slightly. I am working for a proper modification of the config file and then do the PR. I also need edto to port the c_libs from the old libsharp version as it is no longer distributed with the new version. I think the licence allows that.

**Comment by gfabbian** [comment]
It's done and I've submitted a PR. If  @xzackli or others want to check can also pull from my fork. Let me know if edits to the doc are needed or something is not clear or, worse, not working!

**Comment by damonge** [comment]
I'm gonna close this for the time being, since the gitlab version seems to still be under development (or at least it's been changing significantly lately). I'll get back to this once things are stable.
