### ISSUE TITLE
using flatmaps conda install

### ISSUE THREAD

**Issue by bnord** [LSSTDESC/NaMaster#87]
I've installed namaster/pymaster with conda.

When I attempt to import flatmaps (taking from an example from a colleague), flatmaps isn't imported. To use flatmaps, we currently need to download flatmaps.py separately, but this could be confusing later when repo is updated. Is there a better way to access this module?

**Comment by damonge** [comment]
Hi @bnord 
`flatmaps.py` is not really part of NaMaster, but rather a collection of convenience functions I put together for some of our tests. You're more than welcome to use it, but if you're looking for something more sophisticated, the [pixell](https://github.com/simonsobs/pixell) module is a lot more comprehensive, and deals well with flat sky and in generar with any rectangular pixelization.
