### ISSUE TITLE
Binning 

### ISSUE THREAD

**Issue by umilta** [LSSTDESC/NaMaster#88]
Hello,

I successfully installed pymaster with conda. I am trying to reproduce one of your example scripts  (Example 5: using workspaces) and I get the error `AttributeError: type object 'NmtBin' has no attribute 'from_nside_linear'` when trying to create a binning scheme.

Do you have any idea why the function seems not to be present? Which format should the output of this function have? I can write one myself as a workaround...

**Comment by damonge** [comment]
Hi @umilta 
Unfortunately the conda version is outdated with respect to the latest version (which is the one that is currently documented). I'm gonna try to push a new conda version now and will ping you when it's ready. In the meantime, if you're in a rush, you can try installing the current master version.

**Comment by damonge** [comment]
OK, the latest version in conda should now be up to date. Please try it again (making sure that the previous version gets uninstalled first)

**Comment by umilta** [comment]
Now the binning function is working in the conda environment. 
Thanks @damonge!

**Comment by damonge** [comment]
Great!
