### ISSUE TITLE
AttributeError: type object 'NmtBin' has no attribute 'from_nside_linear'

### ISSUE THREAD

**Issue by cscoccola** [LSSTDESC/NaMaster#99]
When trying the first simple example (simple pseudo-Cl computation) given in:

https://namaster.readthedocs.io/en/latest/sample_simple.html

I get the following error:

AttributeError: type object 'NmtBin' has no attribute 'from_nside_linear'

Coming from:
Initialize binning scheme with 4 ells per bandpower
b = nmt.NmtBin.from_nside_linear(nside, 4)

Is this attribute no longer valid? 

Thanks in advance for your reply.

**Comment by damonge** [comment]
Thanks @cscoccola 
Could you check that you're using the latest version of the code?
See this issue we closed a couple of months ago: https://github.com/LSSTDESC/NaMaster/issues/88

**Comment by damonge** [comment]
@cscoccola can I check if you managed to fix this?

**Comment by cscoccola** [comment]
@damonge 
Hola David,
Actually, I haven't solved it. The problem remains when running the examples in the tutorial:

----> 2 b = nmt.NmtBin.from_nside_linear(nside, 4)

AttributeError: type object 'NmtBin' has no attribute 'from_nside_linear'

I have just installed again the pymaster package with conda:
conda install -c conda-forge namaster

Previously, I had updated the conda manager:
 conda update -n base -c defaults conda

I have decided to change the sentence:
b = nmt.NmtBin.from_nside_linear(nside, 4)
by:
b= nmt.NmtBin(nside,nlb=4)

But I would like to know if 'from_nside_linear' should work, and why it's not working in my laptop.

Thanks for your efforts,

Claudia

**Comment by yuhants** [comment]
I had the same issue and reinstalling the latest version solve it.

**Comment by damonge** [comment]
@yuhants thanks a lot for confirming this.

@cscoccola can you make sure you have no lingering installations of namaster before re-installing the very latest version? Essentially, don't reinstall it until you check that python hasn't found some remaining old version.

**Comment by damonge** [comment]
I'm gonna close this, but let me know if it persists

**Comment by cscoccola** [comment]
Sorry for not replying before. Recently, I've made a new installation of the conda environment, and of all of the packages including namaster, and now it's working. I don't know what the problem exactly was, but now it's solved. Thanks David.

**Comment by damonge** [comment]
OK, perfect. thanks for letting me know!
